nome = input('Qual é o seu nome?')
print('Olá ', nome+'!', 'Prazer em te conhecer!')
dia = input ('Em que dia você nasceu?')
mes = input ('Em que mês você nasceu?')
ano = input ('Em que ano você nasceu?')
print('Aaah então você nasceu no dia',dia, 'do mês de',mes,'no ano de',ano+'! Correto?')
print('Vou fazer uma soma, esteja preparado!')
int( num1 =input ('Digite o primeiro numero'))
int( num2 = inpu('Digite o segundo numero'))
print('A soma entre seus dois numeros é', num1+num2)
